### ISSUE TITLE
tongdun滑动验证码代码报错

### ISSUE THREAD

**Issue by iuzhao** [bWhirring/-node-slider-verify#2]
tongdun/index:
58行报错：　data.getBuffer()　is not a function

**Comment by bWhirring** [comment]
@iuzhao 我试了下没有报错，你那边具体的报错原因能贴下吗

**Comment by iuzhao** [comment]
那个问题应该是异步造成，我加了2秒的等待就可以了。

**Comment by iuzhao** [comment]
现在遇到了新的问题，我换了一个机器，npm run 后报错：

unhandledRejection: Error: dlopen(/Users/mymac/dev/crawler/node_modules/canvas/build/Release/canvas.node, 1): Library not loaded: @loader_path/libpangocairo-1.0.0.dylib
  Referenced from: /Users/mymac/dev/crawler/node_modules/canvas/build/Release/canvas.node
  Reason: image not found

想问一下你的node,npm版本号，安装这些modules之前还需要安装其他依赖吗？我开发环境是Mac OS

**Comment by bWhirring** [comment]
@iuzhao https://github.com/Automattic/node-canvas 装canvas的时候需要依赖一些系统库，你看下是不是这个原因，我也是Mac OS，node >= 8 都是可以的

```bash
brew install pkg-config cairo pango libpng jpeg giflib librsvg
```

**Comment by iuzhao** [comment]
按照你的指导，项目已经可以成功跑起来。感谢

**Comment by iuzhao** [comment]
还有一个问题，在计算距离的时候，有个for循环，i表示 背景图片的宽度，那么j表示什么？

**Comment by bWhirring** [comment]
@iuzhao 图片的高度，准确来说是可以通过观察来确定滑块在哪个大致的区间内或者通过计算来得出具体在哪个高度范围内

**Comment by iuzhao** [comment]
明白，这里的j就是缺口的位置的高度
